export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL";
//User
export const DELETE_SUCCESSFUL="DELETE_SUCCESSFUL";
export const UPDATE_SUCESSFUL="UPDATE_SUCCESSFUL";
export const GET_BY_USERNAME="GET_BY_USERNAME";
export const USER_ERROR="USER_ERROR";

export const LOGOUT = "LOGOUT";
