export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL";
//User
export const DELETE_SUCCESSFUL="DELETE_SUCCESSFUL";
export const UPDATE_EMAIL_SUCCESSFUL="UPDATE_EMAIL_SUCCESSFUL";
export const UPDATE_PASSWORD_SUCCESSFUL="UPDATE_PASSWORD_SUCCESSFUL";
export const UPDATE_USERNAME_SUCCESSFUL="UPDATE_USERNAME_SUCCESSFUL";
export const UPDATE_ERROR="UPDATE_ERROR";
export const UPDATE_BIO_SUCCESSFUL="UPDATE_BIO_SUCCESSFUL";
export const GET_BY_USERNAME="GET_BY_USERNAME";
export const USER_ERROR="USER_ERROR";
export const GET_EMAIL="GET_EMAIL";
export const GET_BIO="GET_BIO";

export const LOGOUT = "LOGOUT";
