export const BLOCK_SUCCESSFUL = "BLOCK_SUCCESSFUL";
export const BLOCK_ERROR = "BLOCK_ERROR";
export const GET_ALL_BLOCKED="GET_ALL_BLOCKED";
export const GET_ALL_BLOCKED_BY="GET_ALL_BLOCKED_BY";
export const UNBLOCK_SUCCESSFUL="UNBLOCK_SUCCESSFUL";