export const ADD_FRIEND_SUCCESSFUL = "ADD_FRIEND_SUCCESSFUL";
export const FRIEND_ERROR = "FRIEND_ERROR";
export const UNFRIEND_SUCCESSFUL = "UNFRIEND_SUCCESSFUL";
export const GET_ALL_FRIENDS="GET_ALL_FRIENDS";